// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace radon_group_chr_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 37> locations_array__ =
  {" (found before start of program)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 11, column 2 to column 17)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 12, column 2 to column 16)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 13, column 2 to column 12)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 14, column 2 to column 22)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 15, column 2 to column 24)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 18, column 2 to column 14)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 19, column 2 to column 18)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 21, column 2 to column 27)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 24, column 4 to column 62)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 23, column 2 to line 24, column 62)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 27, column 2 to column 22)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 28, column 2 to column 42)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 30, column 2 to column 21)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 31, column 2 to column 42)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 33, column 2 to column 24)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 34, column 2 to column 43)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 36, column 2 to column 25)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 37, column 2 to column 40)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 39, column 2 to column 27)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 40, column 2 to column 42)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 42, column 2 to column 27)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 43, column 2 to column 48)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 2, column 2 to column 17)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 3, column 2 to column 17)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 4, column 30 to column 31)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 4, column 2 to column 33)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 5, column 9 to column 10)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 5, column 2 to column 14)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 6, column 9 to column 10)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 6, column 2 to column 14)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 7, column 9 to column 10)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 7, column 2 to column 14)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 8, column 2 to column 29)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 12, column 9 to column 10)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 18, column 9 to column 10)",
  " (in '/mnt/c/Windows/System32/example-models-master/ARM/Ch.12/radon_group_chr.stan', line 19, column 9 to column 10)"};
class radon_group_chr_model final : public model_base_crtp<radon_group_chr_model> {
 private:
  int N;
  int J;
  std::vector<int> county;
  Eigen::Matrix<double,-1,1> u_data__;
  Eigen::Matrix<double,-1,1> x_data__;
  Eigen::Matrix<double,-1,1> y_data__;
  double phi;
  Eigen::Map<Eigen::Matrix<double,-1,1>> u{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
 public:
  ~radon_group_chr_model() {}
  radon_group_chr_model(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "radon_group_chr_model_namespace::radon_group_chr_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 23;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 24;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("county", "N", N);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "county", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      county = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 26;
      county = context__.vals_i("county");
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "county", county, 1);
      current_statement__ = 26;
      stan::math::check_less_or_equal(function__, "county", county, J);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("u", "N", N);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "u", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      u_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&u) Eigen::Map<Eigen::Matrix<double,-1,1>>(u_data__.data(), N);
      {
        std::vector<local_scalar_t__> u_flat__;
        current_statement__ = 28;
        u_flat__ = context__.vals_r("u");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 28;
          stan::model::assign(u, u_flat__[(pos__ - 1)],
            "assigning variable u", stan::model::index_uni(sym1__));
          current_statement__ = 28;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 29;
      stan::math::validate_non_negative_index("x", "N", N);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "x", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      x_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&x) Eigen::Map<Eigen::Matrix<double,-1,1>>(x_data__.data(), N);
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 30;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 30;
        pos__ = 1;
        current_statement__ = 30;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 30;
          stan::model::assign(x, x_flat__[(pos__ - 1)],
            "assigning variable x", stan::model::index_uni(sym1__));
          current_statement__ = 30;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 31;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), N);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 32;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 32;
        pos__ = 1;
        current_statement__ = 32;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 32;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 32;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 33;
      context__.validate_dims("data initialization", "phi", "double",
        std::vector<size_t>{});
      phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 33;
      phi = context__.vals_r("phi")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "phi", phi, 0);
      current_statement__ = 33;
      stan::math::check_less_or_equal(function__, "phi", phi, 1);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("eta", "J", J);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("b", "J", J);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("y_hat", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 2 + J + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "radon_group_chr_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "radon_group_chr_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 2;
      eta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      local_scalar_t__ mu_b = DUMMY_VAR__;
      current_statement__ = 3;
      mu_b = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 4;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ sigma_b = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_b = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> b =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> y_hat =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(b,
        stan::math::add(mu_b, stan::math::multiply(sigma_b, eta)),
        "assigning variable b");
      current_statement__ = 10;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 9;
        stan::model::assign(y_hat,
          ((stan::model::rvalue(b, "b",
              stan::model::index_uni(
                stan::model::rvalue(county, "county",
                  stan::model::index_uni(i)))) +
          (stan::model::rvalue(x, "x", stan::model::index_uni(i)) *
          stan::model::rvalue(beta, "beta", stan::model::index_uni(1)))) +
          (stan::model::rvalue(u, "u", stan::model::index_uni(i)) *
          stan::model::rvalue(beta, "beta", stan::model::index_uni(2)))),
          "assigning variable y_hat", stan::model::index_uni(i));
      }
      {
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_b, 0, 1));
        current_statement__ = 12;
        lp_accum__.add((phi * stan::math::normal_lpdf<false>(mu_b, 0, 1)));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(eta, 0, 1));
        current_statement__ = 14;
        lp_accum__.add((phi * stan::math::normal_lpdf<false>(eta, 0, 1)));
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 100));
        current_statement__ = 16;
        lp_accum__.add((phi * stan::math::normal_lpdf<false>(beta, 0, 1)));
        current_statement__ = 17;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma, 0, 2.5));
        current_statement__ = 18;
        lp_accum__.add(stan::math::cauchy_lpdf<false>(sigma, 0, 2.5));
        current_statement__ = 19;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma_b, 0, 2.5));
        current_statement__ = 20;
        lp_accum__.add(stan::math::cauchy_lpdf<false>(sigma_b, 0, 2.5));
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y, y_hat, sigma));
        current_statement__ = 22;
        lp_accum__.add((phi *
          stan::math::normal_lpdf<false>(y, y_hat, sigma)));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "radon_group_chr_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      Eigen::Matrix<double,-1,1> eta =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      eta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      double mu_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      mu_b = in__.template read<local_scalar_t__>();
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double sigma_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma_b = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> b =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> y_hat =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta);
      out__.write(eta);
      out__.write(mu_b);
      out__.write(sigma);
      out__.write(sigma_b);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 8;
      stan::model::assign(b,
        stan::math::add(mu_b, stan::math::multiply(sigma_b, eta)),
        "assigning variable b");
      current_statement__ = 10;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 9;
        stan::model::assign(y_hat,
          ((stan::model::rvalue(b, "b",
              stan::model::index_uni(
                stan::model::rvalue(county, "county",
                  stan::model::index_uni(i)))) +
          (stan::model::rvalue(x, "x", stan::model::index_uni(i)) *
          stan::model::rvalue(beta, "beta", stan::model::index_uni(1)))) +
          (stan::model::rvalue(u, "u", stan::model::index_uni(i)) *
          stan::model::rvalue(beta, "beta", stan::model::index_uni(2)))),
          "assigning variable y_hat", stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        out__.write(b);
        out__.write(y_hat);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(2),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(eta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable eta");
      out__.write(eta);
      local_scalar_t__ mu_b = DUMMY_VAR__;
      current_statement__ = 3;
      mu_b = in__.read<local_scalar_t__>();
      out__.write(mu_b);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 4;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      local_scalar_t__ sigma_b = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_b = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_b);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "eta", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "mu_b", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_b",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> eta_flat__;
        current_statement__ = 2;
        eta_flat__ = context__.vals_r("eta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(eta, eta_flat__[(pos__ - 1)],
            "assigning variable eta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(eta);
      local_scalar_t__ mu_b = DUMMY_VAR__;
      current_statement__ = 3;
      mu_b = context__.vals_r("mu_b")[(1 - 1)];
      out__.write(mu_b);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 4;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
      local_scalar_t__ sigma_b = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_b = context__.vals_r("sigma_b")[(1 - 1)];
      out__.write_free_lb(0, sigma_b);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta", "eta", "mu_b", "sigma",
                "sigma_b"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"b", "y_hat"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(2)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_b");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "sigma_b");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "b" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_hat" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_b");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "sigma_b");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "b" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_hat" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"mu_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"mu_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((2 + J) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((J + N));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((2 + J) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((J + N));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = radon_group_chr_model_namespace::radon_group_chr_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return radon_group_chr_model_namespace::profiles__;
}
#endif